name: rippl
description: "Privacy-first social network client."
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.10.0
  drift: ^2.31.0
  drift_flutter: ^0.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  flutter_secure_storage: ^10.3.1
  flutter_svg: ^2.3.0
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  package_info_plus: ^10.2.1
  riverpod_annotation: ^4.0.3
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.6.0+eol
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  riverpod_generator: ^4.0.4
  freezed: ^3.2.6-dev.1
  json_serializable: ^6.14.0
  drift_dev: ^2.34.0
  alchemist: ^0.14.0
  http_mock_adapter: ^0.6.1
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/
